language: python
matrix:
  include:
    - name: "Python 2.6"
      dist: "trusty"
      python: "2.6"
    - name: "Python 2.7"
      dist: "trusty"
      python: "2.7"
    - name: "Python 3.3"
      python: "3.3"
      dist: "trusty"
    - name: "Python 3.4"
      python: "3.4"
    - name: "Python 3.5"
      python: "3.5"
    - name: "Python 3.6"
      python: "3.6"
    - name: "Python 3.7"
      python: "3.7"
    - name: "Python 3.8"
      python: "3.8"
install:
    - pip install pycodestyle
    # Install a legacy pyflakes to use with Python2.6 since they no longer
    # support installing the project in Python2.6 environments after 2.0.0.
    # We should be able to use any modern version of pyflakes for modern Python
    # installations.
    - if [[ "$(python --version 2>&1)" =~ Python\ (2\.6.*|3\.3.*) ]]; then pip install pyflakes==1.6.0; else pip install pyflakes; fi
    # Similarly, pytest has dropped support for Python 2.6 and 3.2. This
    # installs a legacy version of it for those cases.
    - if [[ "$(python --version 2>&1)" =~ Python\ (3\.2.*|2\.6.*) ]]; then pip install "pytest<3.0.0"; else pip install pytest; fi
    - pip install -e ./
script:
    - pycodestyle daemons/
    - pycodestyle tests/
    - pyflakes daemons/
    - pyflakes tests/
    - py.test tests/
